Added onload function to integrate backend with frontend
enriquejosepadilla/sps21-team1 pull request #6
Opened 2021-04-01 15:11 UTC by rashelrr

Deploying app

2021-04-05 20:05 UTC, enriquejosepadilla requested changes

2021-04-05 20:05 UTC, enriquejosepadilla commented on src/main/webapp/index.html
> +
Please fix merging conflicts.

2021-04-06 23:37 UTC, rashelrr commented on src/main/webapp/index.html
> +
Fixed!

2021-04-07 15:40 UTC, enriquejosepadilla approved these changes

2021-04-07 15:40 UTC, merged